<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" href="<?=dirname($this['url']); ?>/Styles.css"/>
        <link href='http://fonts.googleapis.com/css?family=Junge' rel='stylesheet' type='text/css'>
        <title>Careful Coder MVC Framework</title>
    </head>

    <body>
    <h1>Careful Coder MVC Framework.</h1>
    <div class="bg"></div>
    <div class="stuff">
        <div class="gradientborder top"></div>